baseURL = "https://blog.best-fiber.shop/"
languageCode = "zh-cn"
title = "Oldsheep"

[params]
  description = "我是忽悠老羊，欢迎来到我的站点"
  theme = "theme-base-09"

[[menu.main]]
  name = "首页"
  url = "/"
  identifier = "home"
  weight = 10

[[menu.main]]
  name = "笔记"
  url = "/notes/"
  identifier = "notes"
  weight = 20

[[menu.main]]
  name = "日志"
  url = "/diary/"
  identifier = "diary"
  weight = 30

[[menu.main]]
  name = "友链"
  url = "/links/"
  identifier = "links"
  weight = 40

[[menu.main]]
  name = "关于"
  url = "/about/"
  identifier = "about"
  weight = 50

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/oldsheep113/"
  identifier = "github"
  weight = 60

[[menu.main]]
  name = "哔哩哔哩"
  url = "https://space.bilibili.com/489972934"
  identifier = "bilibili"
  weight = 70
